-- Ancient and Medieval Economic Thought — authored, human-reviewed master.
-- economics/history-of-economics/ancient-and-medieval-economic-thought
-- @ research/advanced/read. The node already exists (History of Economics
-- chapter); this attaches its curated article. Applied by db-migrate after
-- seed.sql; idempotent upsert. {{image}} markers resolve to Wikipedia at read
-- time (see src/components/Reader.tsx). Curated quiz at the bottom.

with master as (
  insert into content (node_id, depth, level, format, body, generated, reviewed)
  values (
    'economics/history-of-economics/ancient-and-medieval-economic-thought',
    'research',
    'advanced',
    'read',
    $am_master$## I. Economics Before Economics

No thinker discussed in this article believed in "the economy." The word's ancestor, Greek *oikonomia*, meant the art of managing a household or estate; the notion of an autonomous sphere of society governed by its own laws — supply and demand, growth, equilibrium — awaited the eighteenth century. Ancient and medieval writers approached what we call economic questions as subdivisions of other inquiries: ethics (what may I charge?), politics (how should the ruler tax?), law (which contracts bind?), and salvation (can a merchant be saved?). Karl Polanyi coined the standard term for this condition: the pre-modern economy was *embedded* — enmeshed in kinship, religion, and politics rather than disembedded into an autonomous market system with its own science.

This creates a methodological trap the whole field has learned to respect. Read the ancients with modern categories and you will find "anticipations" everywhere — a Laffer curve in Ibn Khaldun, subjective value theory in a Franciscan friar, Gresham's law in a French bishop — and the finding is not wrong, but it flatters us into missing what these authors were actually doing. The great historiographical provocations frame the article. Joseph Schumpeter's monumental *History of Economic Analysis* (1954) distinguished economic *thought* (opinions about economic matters, abundant everywhere) from economic *analysis* (the intellectual effort to understand how economic mechanisms work), judged the ancients thin on the latter, and posited a "Great Gap" of five centuries between the Greeks and the scholastics in which, he claimed, nothing analytical happened. The gap, as Section V shows, was not in history but in Schumpeter's reading list: those centuries were the golden age of Islamic economic reasoning. Moses Finley's *The Ancient Economy* (1973) pressed the opposite provocation — that antiquity lacked economic analysis because it lacked "an economy" to analyze, status and citizenship mattering more than markets — a thesis a generation of archaeology and papyrology has heavily qualified. Between these poles, the honest reading treats pre-modern economic thought neither as failed modern economics nor as mere moralizing, but as rigorous reasoning about production, exchange, money, and distribution conducted inside frameworks whose first question was not "what maximizes wealth?" but "what is just?" That question, it turns out, forces most of the analytical machinery into existence anyway — one cannot say what a just price is without a theory of what prices are.

## II. The Ancient Near East: Where the Documents Begin

Economic reasoning is older than economic writing, and economic writing is nearly as old as writing itself — cuneiform originated around 3300 BCE substantially as accounting technology, and the majority of surviving tablets are receipts, loans, leases, and ledgers. From Mesopotamia three durable inventions demand notice. First, **interest**: standardized loan contracts with customary rates — commonly 20% on silver and 33⅓% on barley in Old Babylonian practice — predate coined money by well over a millennium, refuting any theory that interest is unnatural to early societies. Second, **administered prices**: the Code of Hammurabi (c. 1750 BCE) fixes wages for ox-drivers, boatmen, and physicians and sets liability rules — evidence not of a market-free world but of a palace-and-temple economy in which large redistributive institutions coexisted with private trade, the mix Polanyi's followers and their critics still argue over.

{{image: Code of Hammurabi | The stele of Hammurabi (c. 1750 BCE): its laws fix wages and prices — a window onto the palace-and-temple economy in which great institutions and private trade coexisted.}}

Third, and most striking to modern eyes, the **debt cancellation**: Mesopotamian rulers periodically proclaimed "clean slates" (Sumerian *amargi*, the first recorded word for "freedom"), annulling consumer debts, freeing debt-slaves, and returning forfeited land. Michael Hudson has argued these were not utopian gestures but stabilization policy: agrarian interest compounds faster than agrarian output grows, so unchecked debt mathematically concentrates land and labor until the crown's tax and army base erodes; the jubilee reset the system. The Hebrew Bible institutionalized the idea — the sabbatical release of debts (Deuteronomy 15) and the fiftieth-year Jubilee (Leviticus 25) — and bequeathed to the West, along with the Exodus memory of bondage, a suspicion of usury ("thou shalt not lend upon interest to thy brother," Deuteronomy 23:19–20, permitting it to foreigners) whose career runs through this entire article.

## III. Greece: The Household, the Polis, and Aristotle's Long Shadow

Greek reflection begins with scarcity. Hesiod's *Works and Days* (c. 700 BCE) — a farmer-poet's rebuke to his idle brother — grounds the human condition in the gods' hiding of livelihood from men, making labor, thrift, and good *eris* (productive competition) the answer; it is as close as archaic literature comes to an economics of the smallholder. Three centuries later, Xenophon's *Oikonomikos*, the genre-founding dialogue on estate management, contains flashes of genuine analysis: his *Cyropaedia* observes that in small towns one craftsman makes beds, doors, and plows, while in large cities a man may live by making only shoes — indeed only by *stitching* them — tying the division of labor to the extent of the market twenty-two centuries before Adam Smith's pin factory (Smith knew his Xenophon). Plato's *Republic* builds the city itself from the same principle — the city exists because none of us is self-sufficient, and justice is each part doing the work suited to it — though Plato then quarantines his guardian class from property and money entirely, inaugurating the Western tradition of treating commerce as morally corrosive to rulers.

{{image: Aristotle | Aristotle, whose distinction between natural household provision and the limitless pursuit of money — and whose "barren money" — set the terms of two thousand years of argument about exchange and interest.}}

It was Aristotle, however, who set the terms of two thousand years of argument, and he must be read carefully because he was doing something precise. In *Politics* I he distinguishes **oikonomia** — acquisition and use of the goods a household or polis needs for the good life, naturally *limited* because needs are limited — from **chrematistike** in its perverse form: acquisition of money for its own sake, *unlimited* because number has no maximum. Trade for use is natural; trade for accumulation makes the medium into the end. From this follows his notorious condemnation of interest: money exists to facilitate exchange, so breeding money from money (*tokos*, "offspring," the Greek word for interest) is the most unnatural acquisition of all — money is barren. Modern economists wince, but notice what the argument required Aristotle to build: the first systematic account of **money's functions** (medium of exchange arising from the inconveniences of barter, measure of value, store of wealth — *Nicomachean Ethics* V and *Politics* I), including the observation that money is a *nomos* (convention) alterable by the community. And in *Ethics* V, analyzing justice in exchange, he confronts the deepest problem: exchange requires that a builder's product and a shoemaker's product be somehow *commensurable* — equated in proportion — and money is the conventional commensurator; but *what* it measures (need? labor? worth of the persons?) Aristotle leaves tantalizingly unresolved, in a passage (1133a–b) whose ambiguity fed both medieval just-price theory and, much later, Marx's reading of value. He also, in a single aside in *Politics* I, records Thales cornering the olive-press market to prove philosophers could be rich if they cared — the first monopoly anecdote in the literature, complete with the observation that cities sometimes raise revenue the same way.

The limits are as instructive as the achievements. Greek analysis stops where slave labor, contempt for banausic (manual/commercial) occupations, and the citizen-warrior ideal begin; the thinkers theorizing exchange belonged to a class that despised its practitioners. Finley's thesis lives here — and yet fourth-century Athens ran grain-import regulations, maritime loans at risk-adjusted interest, banks, and litigation over all of it, so the gap was between practice and what philosophers deigned to theorize.

## IV. Rome, the Agronomists, and the Early Church

Rome's genius was juridical rather than analytical. Roman law built the conceptual infrastructure later economic thought would presuppose: refined doctrines of property (*dominium*), contract, partnership (*societas*), agency, and the crucial maxim that would echo through a millennium of price theory — *res tantum valet quantum vendi potest*, a thing is worth what it can be sold for. Cicero's *De Officiis*, ranking occupations (agriculture noble, large-scale trade tolerable, small retail and usury sordid), transmitted Greek prejudices to every subsequent century of Latin readers. The agronomists — Cato, Varro, Columella — wrote estate management with real accounting content; Columella's worked example of vineyard profitability (*De Re Rustica* III), whatever its arithmetic sins (he omits amortization of the land improvements he elsewhere describes), is the ancient world's most explicit investment appraisal. Late antiquity added a cautionary macro lesson: Diocletian's Edict on Maximum Prices (301 CE), fixing over a thousand prices and wages on pain of death to fight a debased-coinage inflation, failed so visibly — goods vanished from markets, the law lapsed — that it became the standard historical exhibit on price controls.

Christianity transformed the moral frame. The Gospels' radicalism about wealth (the camel and the needle's eye; the rich fool) and the communal property of Acts posed a question the Church spent centuries domesticating: the patristic synthesis — Clement of Alexandria's *Who Is the Rich Man That Shall Be Saved?*, the Cappadocians' thunderous sermons on famine profiteers, Ambrose and John Chrysostom on the poor's claim — settled on wealth as stewardship: property is licit, attachment is not, and superfluity belongs, by justice and not merely charity, to the needy. Augustine contributed two load-bearing ideas: private property is not natural but a remedial institution of the fallen condition, held under human law and answerable to it; and — in a passing observation with a long future (*City of God* XI.16) — the prices men pay track not the natural hierarchy of being but human wants: a horse often fetches more than a slave, a jewel more than a servant girl. Value, that is, lies in estimation and use — a seed of subjective value theory planted in a theological argument about creation. On usury, the Church hardened Deuteronomy into general prohibition (Councils of Nicaea for clergy, later extended to laity), setting up the medieval drama of Section VII.

## V. Looking East: Kautilya, the Guanzi, and the Debate Over Salt and Iron

Any account confined to the Mediterranean falsifies the record, for the era's most sophisticated *policy* economics was Asian. The **Arthashastra** attributed to Kautilya (Chanakya), minister to Chandragupta Maurya (c. 300 BCE, with later strata), is a manual of statecraft whose economic apparatus startles first-time readers: detailed tax schedules with the maxim that the king should gather revenue as the bee takes honey — without harming the flower; state price inspectors and profit-margin caps (5% on domestic, 10% on imported goods in one passage); wage schedules; interest ceilings graded by risk (higher for sea voyages); famine stores; and cost-benefit reasoning about irrigation and mines. It is administration, not analysis — there is no curiosity about *why* prices form — but as evidence of what a bureaucratic state could already systematize, it has no Western peer.

{{image: Chanakya | Kautilya (Chanakya), to whom the Arthashastra is attributed — a manual of statecraft with graded interest ceilings, profit-margin caps, and the maxim that the king should take revenue as the bee takes honey, without harming the flower.}}

Chinese thought offers the era's most genuine *theoretical* economics of policy. The **Guanzi** (compiled c. 4th–1st century BCE) develops the *qingzhong* ("light and heavy") theory: goods are "heavy" (dear) when scarce or hoarded, "light" (cheap) when abundant — money and grain stand in reciprocal light/heavy relation — and the ruler should stabilize by buying when grain is light and selling when heavy, the intellectual foundation of the **ever-normal granary**, an institution China operated intermittently for two millennia (and which, via Henry Wallace's reading, influenced the design of New Deal agricultural policy — perhaps the longest policy transmission in economic history). In 81 BCE the Han court staged the **Discourses on Salt and Iron**, a recorded debate between Legalist-leaning ministers defending state monopolies on salt and iron (revenue for frontier defense, price stabilization) and Confucian literati attacking them (the state should not compete with the people for profit; monopolies breed corruption and shoddy goods) — point for point, a state-versus-market debate readable today with eerie familiarity. And the historian **Sima Qian** (c. 100 BCE), in his chapter on the money-makers (*Shiji* 129), articulated as clear a statement of spontaneous order as antiquity produced anywhere: each man pursuing his own occupation and delighting in his own business is like water flowing downward, day and night without ceasing — things appear unbidden and the market needs no summons; the best policy is to leave it alone, the worst is to compete with it. That both the interventionist Guanzi and Sima Qian's laissez-faire coexisted in the same tradition is a useful antidote to civilizational essentialism.

## VI. The Islamic Centuries: Filling Schumpeter's Gap

Between roughly 750 and 1400, the most searching economic reasoning on earth occurred in Arabic. The context mattered: Islam sacralized commerce as no prior tradition had — the Prophet was a merchant, the Qur'an "permits trade and forbids riba" (2:275) — and the Abbasid world ran a commercial system spanning from al-Andalus to China, complete with partnership forms (*mudaraba*, the sleeping-partner/traveling-agent contract that is the probable ancestor of the Italian *commenda*), transfer instruments (*suftaja*, *hawala* — the latter's name survives in modern informal remittance networks and in the very word *aval* on European bills), and sophisticated jurisprudence to govern it all. Theory followed practice. **Abu Yusuf** (d. 798), chief judge to Harun al-Rashid, wrote the *Kitab al-Kharaj* on public finance, arguing for proportional shares of crop over fixed land taxes (better incentives, automatic drought relief) and — against his caliph's intuition — that prices are not simply set by supply: dearness and cheapness come from God's providence working through causes the ruler cannot decree away, an early insistence that prices obey mechanisms, not commands. **Al-Ghazali** (d. 1111), in the economic sections of his *Revival of the Religious Sciences*, gives a strikingly complete treatment of money: it exists because barter requires the double coincidence of wants; it is a mirror that has no color of its own but reflects all values; hoarding it imprisons the ruler's servant; counterfeiting is a sin against the whole community worse than theft from one man — and from the mirror image he re-derives the usury prohibition (making the measure into merchandise perverts its office). He also describes the division of labor in concrete detail — the needle useful only after passing through some twenty-five hands, the loaf of bread arriving only through the successive labor of farmer, miller, baker, and the smiths and carpenters who equip them — and grades occupations by social necessity — farming, weaving, and building as *fard kifaya*, communally obligatory callings.

{{image: Ibn Khaldun | Ibn Khaldun, whose Muqaddimah (1377) tied a civilization's wealth to the division of labor and warned that a dynasty's rising taxes eventually destroy the base they feed on.}}

**Ibn Taymiyyah** (d. 1328) supplied the era's clearest supply-and-demand statement: it is a mistake, he wrote, to blame every price rise on sellers' injustice — dearness may arise from fall in supply or growth in population and demand, and such prices are "in God's hands"; price regulation is licit only against genuine market corruption (collusion, hoarding in famine). And then there is **Ibn Khaldun** (d. 1406), whose *Muqaddimah* (1377) — the "Prolegomena" to a universal history — is the closest any pre-modern work comes to social science entire. Its economic core: civilization's wealth rests on labor and on the division of labor ("individual man cannot obtain his necessities alone"); cities enable specialization, which raises productivity, income, and demand in a cumulative circle; crafts and sciences are luxuries of dense settlement. Over this he lays his famous dynamic: conquering groups bound by *asabiyyah* (social solidarity) found dynasties; success breeds luxury, taxation, and the decay of solidarity; and — in the passage every public-finance economist eventually encounters — at a dynasty's start, low taxes yield large revenue, while at its end, high taxes yield small revenue, because rising imposts destroy the incentive to cultivate and trade until the tax base itself collapses. The reasoning is incentive-based and general-equilibrium in spirit, embedded in a cyclical theory of the state; that it was unknown to Adam Smith and rediscovered by Europe only in the nineteenth century is the standing rebuke to any linear history of the discipline. Modern scholarship (Ghazanfar, Islahi, Essid) has made the point stick: Schumpeter's Great Gap was a gap in transmission and attention, not in thought — though transmission did occur underground, since the scholastics to whom we now turn read their Aristotle in translations from the Arabic, wrapped in Muslim commentary.

## VII. The Scholastics: Just Price, Usury, and the Analysis Justice Required

Latin Europe's economic thought awakened when its economy did. The "commercial revolution" of the eleventh through thirteenth centuries — reborn towns, the Champagne fairs, Italian merchant-banking houses, bills of exchange, double-entry's ancestors — confronted a Church whose inherited doctrine had been formed for a world of manors and mistrust of merchants. The response was the greatest sustained project of the age's intellectual life: the scholastic effort, in universities from Bologna to Oxford, to determine when exchange, price, and payment for money's use were *just* — an inquiry conducted with lawyer's precision (the rediscovered Roman law and the Church's own canon law were half the toolkit) and Aristotle's newly translated works as the other half. Two doctrines organized everything.

{{image: Thomas Aquinas | Thomas Aquinas, who identified the just price with the common estimation of the market — a price that varies with scarcity and need, and forbids not profit but force and fraud.}}

**The just price.** What may a seller charge? The temptation is to imagine the scholastics computing prices from labor or status; the surviving texts mostly say otherwise. The mature doctrine, in Albertus Magnus and above all **Thomas Aquinas** (*Summa Theologiae* II-II, q. 77), identifies the just price with the *communis aestimatio* — the common estimation of the market — a price that varies with time, place, scarcity, and need, not a metaphysical constant. Aquinas's celebrated wheat merchant makes the logic vivid: a seller arriving at a famine-struck town, knowing (as buyers do not) that relief ships follow behind him, may licitly sell at the current high price — disclosure would be generous but is not owed in justice — because the just price is the *present* market price, information asymmetry and all. What the doctrine forbade was not profit but *force and fraud*: exploiting an individual's desperation in a private transaction, collusion, false measure, concealment of defects. Later scholastics sharpened the analysis. The Franciscan **Peter Olivi** (d. 1298) — whose economic writings, long suppressed under suspicion of heresy and rediscovered in the twentieth century, may be the era's most original — decomposed value into *virtuositas* (objective usefulness), *raritas* (scarcity), and *complacibilitas* (subjective desirability), and treated price as reflecting aggregated, probability-weighted estimation in a community; **Jean Buridan** (d. c. 1361) added that value is measured by *human need* rather than intrinsic dignity (echoing Augustine's horse and slave), and that the needs in question are those of the community, not the individual pair of traders; **San Bernardino of Siena** and **Antoninus of Florence** in the fifteenth century carried Olivi's triad into preaching and added a frank appreciation of the merchant's and entrepreneur's socially useful skill — rare, laborious, risk-bearing, and thus justly compensated. The scholarly verdict (Raymond de Roover's revisionist essays, Odd Langholm's exhaustive corpus studies) is that scholastic price theory was predominantly a market-utility-scarcity theory constrained by an ethics of coercion — closer, structurally, to modern value theory than to the labor theories of the classical economists who came between.

**Usury.** On payment for loans the same minds reached the opposite of laissez-faire, and understanding *why* is the entry ticket to the medieval mind. A loan (*mutuum*) transfers ownership of a fungible — money, grain, wine consumed in use; charging for use *beyond* return of principal, the argument ran, sells something that does not exist (Aquinas: selling the wine and the drinking of the wine separately), or sells time itself, which belongs to God and to all; behind the metaphysics stood Aristotle's barren money and the Gospel's *mutuum date nihil inde sperantes* (Luke 6:35). The prohibition was serious law — Lateran III (1179) denied usurers Christian burial — and yet commerce needed credit, so the doctrine developed the way serious law does: by distinction. *Extrinsic titles* justified payment that was not, formally, usury: *damnum emergens* (compensation for loss suffered by the lender), and — accepted more warily — *lucrum cessans* (compensation for profit forgone, an opportunity-cost concept in embryo); *risk* transformed the transaction entirely, since in a partnership (*societas*) or sea loan the capitalist shared the venture's peril and his gain was profit, not usury; the *census* (purchase of an income stream), the bill of exchange (formally a currency transaction across places, with the interest folded into the exchange rate), and eventually the "triple contract" wrapped licit forms around economic lending. Historians differ on the ledger: the prohibition channeled capital toward equity-like, risk-sharing instruments (arguably a virtue), spawned ingenious financial engineering, burdened the poor's small credit (partly answered by the Franciscan *montes pietatis*, charitable pawn banks, from 1462), and fed a poisonous side-channel — the confinement of licensed moneylending to Jews, with consequences written across European history. Analytically, the long argument forced into existence the concepts — capital as fruitful, opportunity cost, risk premium, discounting — that would eventually dissolve the prohibition itself.

## VIII. Money, Princes, and the First Treatise: Oresme

One more medieval achievement deserves separate standing. Coin debasement was the fiscal temptation of every hard-pressed prince — reduce the silver, keep the face value, pocket the difference — and fourteenth-century France, financing the Hundred Years' War, debased serially.

{{image: Nicole Oresme | Nicole Oresme, whose De Moneta (c. 1358) — plausibly the first Western treatise on a single economic subject — held that money belongs to the community and that debasement is counterfeiting from the throne.}}

Against this practice **Nicole Oresme** (d. 1382), theologian, mathematician, and bishop, wrote *De Moneta* (c. 1358), plausibly the first Western treatise devoted to a single economic subject. Its theses: money, though coined by the prince, *belongs to the community* whose exchanges it serves; its value rests on the integrity of its standard; alteration for profit is worse than usury — it is counterfeiting from the throne, a hidden tax levied without consent that disrupts every contract and drives good money abroad while bad circulates at home (the observation later mislabeled "Gresham's law," visible already in the Guanzi and in Aristophanes' *Frogs*). Buridan's and Oresme's Paris gave monetary theory its first home; the quantity-theoretic and constitutional questions they opened — who owns the standard? what may the sovereign do to it? — run directly to the sixteenth-century School of Salamanca (where Martín de Azpilcueta, confronting American silver, stated the quantity theory of money and purchasing-power reasoning outright) and thence into the modern discipline. Salamanca is the bridge out of our period: scholastic in method, early-modern in problems, and the acknowledged ancestor — via Grotius and Pufendorf — of the natural-law framework in which Adam Smith was trained.

## IX. Synthesis: What This Tradition Was, and What It Left

Step back from the parade of authors and three summary judgments organize the whole.

First, pre-modern economic thought was **ethics-first, and analytical because of it, not despite it**. The just-price question forced a theory of value and price formation; the usury question forced theories of capital, risk, time, and opportunity cost; the taxation question (Abu Yusuf, Ibn Khaldun) forced incentive analysis; the debasement question forced monetary theory. Justice was the research program, and mechanism its unavoidable by-product — a genealogy worth remembering in an age tempted to believe the arrow runs only from positive analysis to normative conclusion.

Second, the tradition's **silences map its social world**. Slavery is everywhere in the economies and almost nowhere problematized in the economics; women's labor sustains every household in an *oikonomia* literature addressed to male heads; growth — the master concept of modern economics — is nearly absent, because in an organic economy expanding at glacial rates, the stationary state was not a theory but a description, and the analytically live questions were distribution and stability. Where sustained growth-like reasoning does appear — Ibn Khaldun's cumulative urban division of labor — it is embedded in a cycle, not a trend.

Third, the **continuities into modernity are real but crooked**. The line from Aristotle's commensurability problem through Olivi's and Buridan's utility-scarcity value theory to Salamanca and (as Schumpeter himself argued, and as the Austrian school delights in repeating) to the subjectivist strand of modern economics is documentable; so is the line from scholastic natural law to Smith's *Theory of Moral Sentiments* and *Wealth of Nations*; so is the transmission of Greek thought through Arabic hands, and of partnership and credit instruments from the Islamic Mediterranean into Italian practice. But the eighteenth century's decisive move — imagining the economy as a self-regulating system whose outcomes are legitimate *because* systemic — was a genuine rupture with a tradition for which every price and every loan remained, finally, an act between persons answerable to justice. Whether that rupture was emancipation or amnesia is not a question history settles; it is the question this material equips you to argue.

---

## Further Reading

- **Joseph Schumpeter, *History of Economic Analysis* (1954), Part II.** The erudite, opinionated foundation — and the source of the "Great Gap" thesis this article contests.
- **S. M. Ghazanfar (ed.), *Medieval Islamic Economic Thought* (2003).** The collection that dismantles Schumpeter's gap.
- **Odd Langholm, *Economics in the Medieval Schools* (1992).** The exhaustive corpus study of scholastic value, price, and usury theory.
- **Diana Wood, *Medieval Economic Thought* (2002).** The best accessible synthesis of the medieval material.
- **Raymond de Roover, *Business, Banking, and Economic Thought* (1974).** The revisionist essays that reset the just-price debate.
- **M. I. Finley, *The Ancient Economy* (1973).** The provocation that antiquity had no "economy" to analyze — read with the countervailing *Cambridge Economic History of the Greco-Roman World* (2007).
- **Michael Hudson, *…and forgive them their debts* (2018).** On Near Eastern debt cancellation and the jubilee tradition.
- **Ibn Khaldun, *The Muqaddimah* (Rosenthal translation, Dawood abridgment).** Short enough to read whole — and should be.
- **Nicole Oresme, *De Moneta* (Johnson translation, c. 1358).** The first Western treatise devoted to a single economic subject.
- **The *Guanzi* (Rickett translation) and Esson Gale's *Discourses on Salt and Iron*.** The points of entry to the Chinese policy tradition.$am_master$,
    true,
    true
  )
  on conflict (node_id, depth, level, format) do update
    set body = excluded.body, generated = excluded.generated, reviewed = excluded.reviewed
    where content.body is distinct from excluded.body
       or content.generated is distinct from excluded.generated
       or content.reviewed is distinct from excluded.reviewed
  returning node_id
)
delete from content
where node_id in (select node_id from master)
  and not (depth = 'research' and level = 'advanced' and format = 'read');

-- Curated, human-reviewed quiz — same set served at every level.
with q as (
  select $am_quiz$[
    {"id":"q1","type":"mcq","prompt":"The Greek word oikonomia — the ancestor of 'economy' — originally referred to:","options":["The management of a household or estate","A self-regulating market system","The minting of coins by the state","The study of national wealth"],"answerIndex":0,"explanation":"Oikonomia meant the art of managing a household or estate. The idea of an autonomous 'economy' governed by its own laws (supply, demand, growth, equilibrium) is an eighteenth-century invention; pre-modern writers treated economic questions as parts of ethics, politics, and law."},
    {"id":"q2","type":"mcq","prompt":"Schumpeter's thesis of a 'Great Gap' — five analytically empty centuries between the Greeks and the scholastics — is best refuted by:","options":["Roman legal writing on contract","The golden age of Islamic economic reasoning (c. 750–1400)","Diocletian's price edict","The Hebrew Jubilee laws"],"answerIndex":1,"explanation":"Those centuries were the most fertile period of economic reasoning on earth, in Arabic — Abu Yusuf, al-Ghazali, Ibn Taymiyyah, Ibn Khaldun. The 'gap' was in Schumpeter's reading list, not in history; the scholastics even read their Aristotle in translations from the Arabic."},
    {"id":"q3","type":"mcq","prompt":"Aristotle condemned lending money at interest primarily on the grounds that:","options":["It was forbidden by Greek law","Money is 'barren' — breeding money from money makes the medium of exchange into an end in itself","Interest rates were always too high","It competed with the state's revenue"],"answerIndex":1,"explanation":"Aristotle argued money exists to facilitate exchange, so making it 'breed' more money (tokos, 'offspring') is the most unnatural form of acquisition — money is barren. This 'barren money' idea ran through the scholastic usury doctrine for two thousand years."},
    {"id":"q4","type":"mcq","prompt":"For Thomas Aquinas, the 'just price' of a good was essentially:","options":["The cost of the labor and materials that went into it","A fixed value set by the Church","The common estimation of the market (communis aestimatio), varying with scarcity and need","Whatever the poorest buyer could afford"],"answerIndex":2,"explanation":"Aquinas identified the just price with the communis aestimatio — the market's common estimation — which varies with time, place, scarcity, and need. The doctrine forbade force and fraud (coercion, collusion, false measure), not profit itself. It was closer to a market-utility-scarcity theory than to a labor theory of value."},
    {"id":"q5","type":"open","prompt":"The article argues pre-modern economic thought was 'ethics-first, and analytical because of it, not despite it.' Explain what this means, with at least two examples of a moral question forcing an analytical tool into existence.","rubric":"The claim is that because these thinkers began from 'what is just?' rather than 'what maximizes wealth?', the ethical questions dragged analytical machinery into being as a by-product. Examples (any two): the JUST-PRICE question forced a theory of value and price formation (what IS a price? — market estimation, scarcity, utility); the USURY question forced theories of capital, risk, time, and opportunity cost (lucrum cessans, damnum emergens, risk-sharing partnerships); the TAXATION question (Abu Yusuf, Ibn Khaldun) forced incentive analysis; the DEBASEMENT question (Oresme) forced monetary theory. Justice was the research program; mechanism was its unavoidable output."},
    {"id":"q6","type":"open","prompt":"Summarize Ibn Khaldun's insight about taxation over the life of a dynasty, and explain the incentive logic behind it.","rubric":"Ibn Khaldun observed that at a dynasty's start, LOW tax rates yield LARGE total revenue, while at its end, HIGH rates yield SMALL revenue. The logic is incentive-based: low imposts leave cultivators and traders the reward for their effort, so production and the tax base expand; as a dynasty ages it grows luxurious and raises rates, which destroys the incentive to produce and trade, shrinking the base until total revenue collapses. The reasoning anticipates the modern 'Laffer curve' but is embedded in his cyclical theory of the state (rising luxury and the decay of asabiyyah/social solidarity)."}
  ]$am_quiz$::jsonb as questions
)
insert into quizzes (node_id, level, questions, generated)
select 'economics/history-of-economics/ancient-and-medieval-economic-thought', lvl, q.questions, true
from q, (values ('easy'), ('advanced'), ('expert')) as l(lvl)
on conflict (node_id, level) do update
  set questions = excluded.questions, generated = excluded.generated;
