/**
 * Regenerate supabase/seed.sql from src/lib/seed.ts.
 *
 *   npm run gen:seed
 *
 * Emits an UPSERT-style seed: subjects and nodes are inserted or updated in
 * place, and only rows that fell out of the taxonomy are deleted. Cached
 * generated content/quizzes are keyed by node id and cascade-delete with their
 * node, so they survive for every node whose id is unchanged — a taxonomy
 * tweak no longer throws away (and re-buys) the whole content cache.
 */
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { SEED_SUBJECTS, SEED_NODES } from "../src/lib/seed";

const q = (s: string | null) => (s === null ? "null" : `'${s.replace(/'/g, "''")}'`);

const lines: string[] = [
  "-- Periergia seed data — unified taxonomy (Subject → Sub-subject → Topic)",
  "-- GENERATED by scripts/gen-seed-sql.ts — edit src/lib/seed.ts and run `npm run gen:seed`.",
  "-- Run AFTER schema.sql. Upserts in place and prunes rows no longer in the",
  "-- seed, so cached content/quizzes survive for nodes whose ids are unchanged.",
  "",
  "begin;",
  "",
  "insert into subjects (id, name, slug, description, position) values",
  SEED_SUBJECTS.map(
    (s) => `  (${q(s.id)}, ${q(s.name)}, ${q(s.slug)}, ${q(s.description)}, ${s.position})`,
  ).join(",\n") + "",
  "on conflict (id) do update set",
  "  name = excluded.name, slug = excluded.slug,",
  "  description = excluded.description, position = excluded.position;",
  "",
];

// Nodes shallow-first so parent_id FKs resolve within the script.
const maxDepth = Math.max(...SEED_NODES.map((n) => n.depth));
for (let d = 0; d <= maxDepth; d++) {
  const batch = SEED_NODES.filter((n) => n.depth === d).sort(
    (a, b) => a.id.localeCompare(b.id) || a.position - b.position,
  );
  if (!batch.length) continue;
  lines.push(
    `-- depth ${d}`,
    "insert into nodes (id, subject_id, parent_id, title, slug, summary, position, depth) values",
    batch
      .map(
        (n) =>
          `  (${q(n.id)}, ${q(n.subjectId)}, ${q(n.parentId)}, ${q(n.title)}, ${q(n.slug)}, ${q(n.summary)}, ${n.position}, ${n.depth})`,
      )
      .join(",\n"),
    "on conflict (id) do update set",
    "  subject_id = excluded.subject_id, parent_id = excluded.parent_id,",
    "  title = excluded.title, slug = excluded.slug, summary = excluded.summary,",
    "  position = excluded.position, depth = excluded.depth;",
    "",
  );
}

lines.push(
  "-- Prune rows that are no longer in the seed (cascades their cached content).",
  "delete from nodes where not (id = any (array[",
  SEED_NODES.map((n) => `  ${q(n.id)}`).join(",\n"),
  "]));",
  "",
  "delete from subjects where not (id = any (array[",
  SEED_SUBJECTS.map((s) => `  ${q(s.id)}`).join(",\n"),
  "]));",
  "",
  "commit;",
  "",
);

const out = resolve(process.cwd(), "supabase/seed.sql");
writeFileSync(out, lines.join("\n"));
console.log(
  `✓ Wrote ${out}: ${SEED_SUBJECTS.length} subjects, ${SEED_NODES.length} nodes (upsert + prune).`,
);
